

# html lang
language: en
theme: 0

# main menu navigation
menu:
  HOME: /
  ARCHIVE: /archives/
  ABOUT: /about/

connect:
  # weibo: /
  github: https://github.com/caijinyc
  # twitter: /
  juejin: https://juejin.im/user/5acc88a8f265da23a2297002
  zhihu: https://www.zhihu.com/people/adherds/activities

# Miscelaneous
favicon: /favicon.ico

# your disqus shortname
disqus: orbem

